In [1]:
import numpy as np
import pandas as pd

In [2]:
cars_data = pd.read_csv(r'cars.csv',header = None)
cars_data.head()

0      1  2  3      4     5      6
0  vhigh  vhigh  2  2  small   low  unacc
1  vhigh  vhigh  2  2  small   med  unacc
2  vhigh  vhigh  2  2  small  high  unacc
3  vhigh  vhigh  2  2    med   low  unacc
4  vhigh  vhigh  2  2    med   med  unacc

In [3]:
cars_data.shape

(1728, 7)

In [4]:
cars_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       1728 non-null   object
 1   1       1728 non-null   object
 2   2       1728 non-null   object
 3   3       1728 non-null   object
 4   4       1728 non-null   object
 5   5       1728 non-null   object
 6   6       1728 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB


In [5]:
cars_data.columns=['buying','maint','doors','persons','lug_boot','safety','classes']

In [6]:
cars_data.head()

buying  maint doors persons lug_boot safety classes
0  vhigh  vhigh     2       2    small    low   unacc
1  vhigh  vhigh     2       2    small    med   unacc
2  vhigh  vhigh     2       2    small   high   unacc
3  vhigh  vhigh     2       2      med    low   unacc
4  vhigh  vhigh     2       2      med    med   unacc

In [7]:
cars_data.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
classes     0
dtype: int64

In [8]:
cars_df = pd.DataFrame(cars_data)

In [9]:
colname = cars_df.columns
colname

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'classes'], dtype='object')

In [10]:
## converting categorical into numerical
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
for x in colname:
    cars_df[x] = le.fit_transform(cars_df[x])
    le_name_mapping = dict(zip(le.classes_,le.transform(le.classes_)))
    print('Feature', x)
    print('mapping', le_name_mapping)

Feature buying
mapping {'high': 0, 'low': 1, 'med': 2, 'vhigh': 3}
Feature maint
mapping {'high': 0, 'low': 1, 'med': 2, 'vhigh': 3}
Feature doors
mapping {'2': 0, '3': 1, '4': 2, '5more': 3}
Feature persons
mapping {'2': 0, '4': 1, 'more': 2}
Feature lug_boot
mapping {'big': 0, 'med': 1, 'small': 2}
Feature safety
mapping {'high': 0, 'low': 1, 'med': 2}
Feature classes
mapping {'acc': 0, 'good': 1, 'unacc': 2, 'vgood': 3}


In [11]:
cars_df.head()

buying  maint  doors  persons  lug_boot  safety  classes
0       3      3      0        0         2       1        2
1       3      3      0        0         2       2        2
2       3      3      0        0         2       0        2
3       3      3      0        0         1       1        2
4       3      3      0        0         1       2        2

In [12]:
cars_data.classes.value_counts()

#acc==>0
#good==>1
#unacc==>2
#vgood==>3

2    1210
0     384
1      69
3      65
Name: classes, dtype: int64

In [13]:
X = cars_df.values[:,:-1]
Y = cars_df.values[:,-1]
Y = Y.astype(int)

In [14]:
X.shape

(1728, 6)

In [15]:
Y.shape

(1728,)

In [16]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3,random_state = 10)

In [18]:
### Decision Tree model
from sklearn.tree import DecisionTreeClassifier
model_DecisionTree = DecisionTreeClassifier(criterion = 'gini', min_samples_leaf = 5, max_depth=10, random_state=10)
model_DecisionTree.fit(X_train,Y_train)

DecisionTreeClassifier(max_depth=10, min_samples_leaf=5, random_state=10)

In [19]:
Y_pred = model_DecisionTree.predict(X_test)

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[ 92   6   4   0]
 [  0  17   2   2]
 [  8   0 363   0]
 [  3   5   0  17]]
0.9421965317919075
              precision    recall  f1-score   support

           0       0.89      0.90      0.90       102
           1       0.61      0.81      0.69        21
           2       0.98      0.98      0.98       371
           3       0.89      0.68      0.77        25

    accuracy                           0.94       519
   macro avg       0.84      0.84      0.84       519
weighted avg       0.95      0.94      0.94       519



In [21]:
print(list(zip(cars_df.columns,model_DecisionTree.feature_importances_)))

[('buying', 0.15391565199335028), ('maint', 0.2699990515342031), ('doors', 0.03511651586061642), ('persons', 0.18449221442490638), ('lug_boot', 0.08402440114201538), ('safety', 0.2724521650449083)]


In [22]:
from sklearn import tree
with open("model_DecisionTree.txt", "w") as f:
    
    f = tree.export_graphviz(model_DecisionTree, feature_names=cars_df.columns[:-1],
                             out_file=f)
    
#generate the file and upload the code in webgraphviz.com to plot the decision tree

In [23]:
from sklearn import svm
classifier=svm.SVC(kernel="rbf", gamma=0.1, C=1)
#fitting training data to the model
classifier.fit(X_train,Y_train)

Y_pred=classifier.predict(X_test)
#print(list(zip(Y_test,Y_pred)))

In [24]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[ 82   0  20   0]
 [ 21   0   0   0]
 [ 17   0 354   0]
 [ 17   0   0   8]]
0.8554913294797688
              precision    recall  f1-score   support

           0       0.60      0.80      0.69       102
           1       0.00      0.00      0.00        21
           2       0.95      0.95      0.95       371
           3       1.00      0.32      0.48        25

    accuracy                           0.86       519
   macro avg       0.64      0.52      0.53       519
weighted avg       0.84      0.86      0.84       519



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [25]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=8, 
                               metric='euclidean')
#fit the model on the data and predict the values
model_KNN.fit(X_train,Y_train)

Y_pred=model_KNN.predict(X_test)
#print(list(zip(Y_test,Y_pred)))

In [26]:
int(np.sqrt(len(X_train)))

34

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[ 97   1   4   0]
 [  8  12   0   1]
 [ 10   0 361   0]
 [  3   0   0  22]]
0.9479768786127167
              precision    recall  f1-score   support

           0       0.82      0.95      0.88       102
           1       0.92      0.57      0.71        21
           2       0.99      0.97      0.98       371
           3       0.96      0.88      0.92        25

    accuracy                           0.95       519
   macro avg       0.92      0.84      0.87       519
weighted avg       0.95      0.95      0.95       519



In [28]:
from sklearn.linear_model import LogisticRegression
#create a model
classifier=LogisticRegression()
#fitting training data to the model
classifier.fit(X_train,Y_train)

Y_pred=classifier.predict(X_test)
#print(list(zip(Y_test,Y_pred)))

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[ 19   0  78   5]
 [  3   0  18   0]
 [ 30   0 339   2]
 [  8   0  14   3]]
0.6955684007707129
              precision    recall  f1-score   support

           0       0.32      0.19      0.23       102
           1       0.00      0.00      0.00        21
           2       0.76      0.91      0.83       371
           3       0.30      0.12      0.17        25

    accuracy                           0.70       519
   macro avg       0.34      0.31      0.31       519
weighted avg       0.62      0.70      0.65       519



C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [32]:
#predicting using the Bagging_Classifier
from sklearn.ensemble import ExtraTreesClassifier

model=ExtraTreesClassifier(n_estimators=100,random_state=10, )
#fit the model on the data and predict the values
model=model.fit(X_train,Y_train)

Y_pred=model.predict(X_test)

In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[101   1   0   0]
 [  3  18   0   0]
 [  1   0 370   0]
 [  1   2   0  22]]
0.9845857418111753
              precision    recall  f1-score   support

           0       0.95      0.99      0.97       102
           1       0.86      0.86      0.86        21
           2       1.00      1.00      1.00       371
           3       1.00      0.88      0.94        25

    accuracy                           0.98       519
   macro avg       0.95      0.93      0.94       519
weighted avg       0.98      0.98      0.98       519



In [34]:
#predicting using the Random_Forest_Classifier
from sklearn.ensemble import RandomForestClassifier

model_RandomForest=RandomForestClassifier(n_estimators=101, random_state=10)

#fit the model on the data and predict the values
model_RandomForest.fit(X_train,Y_train)

Y_pred=model_RandomForest.predict(X_test)


In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[ 99   3   0   0]
 [  1  19   0   1]
 [  2   0 369   0]
 [  2   0   0  23]]
0.9826589595375722
              precision    recall  f1-score   support

           0       0.95      0.97      0.96       102
           1       0.86      0.90      0.88        21
           2       1.00      0.99      1.00       371
           3       0.96      0.92      0.94        25

    accuracy                           0.98       519
   macro avg       0.94      0.95      0.95       519
weighted avg       0.98      0.98      0.98       519



In [36]:
#predicting using the AdaBoost_Classifier
from sklearn.ensemble import AdaBoostClassifier

model_AdaBoost=AdaBoostClassifier(base_estimator=DecisionTreeClassifier(random_state=10),
                                  n_estimators=10,
                                  random_state=10)
#fit the model on the data and predict the values
model_AdaBoost.fit(X_train,Y_train)
Y_pred=model_AdaBoost.predict(X_test)

In [37]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[ 99   2   1   0]
 [  4  17   0   0]
 [  0   0 371   0]
 [  1   0   0  24]]
0.9845857418111753
              precision    recall  f1-score   support

           0       0.95      0.97      0.96       102
           1       0.89      0.81      0.85        21
           2       1.00      1.00      1.00       371
           3       1.00      0.96      0.98        25

    accuracy                           0.98       519
   macro avg       0.96      0.94      0.95       519
weighted avg       0.98      0.98      0.98       519



In [38]:
model_AdaBoost.estimator_errors_

array([0., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [39]:
#predicting using the Gradient_Boosting_Classifier
from sklearn.ensemble import GradientBoostingClassifier

model_GradientBoosting=GradientBoostingClassifier(n_estimators=150,
                                                  random_state=10)

#fit the model on the data and predict the values
model_GradientBoosting.fit(X_train,Y_train)

Y_pred=model_GradientBoosting.predict(X_test)

In [40]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[101   1   0   0]
 [  0  21   0   0]
 [  0   0 371   0]
 [  0   0   0  25]]
0.9980732177263969
              precision    recall  f1-score   support

           0       1.00      0.99      1.00       102
           1       0.95      1.00      0.98        21
           2       1.00      1.00      1.00       371
           3       1.00      1.00      1.00        25

    accuracy                           1.00       519
   macro avg       0.99      1.00      0.99       519
weighted avg       1.00      1.00      1.00       519



In [41]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier

In [42]:
# create the sub models
estimators = []
#model1 = LogisticRegression()
#estimators.append(('log', model1))
model2 = DecisionTreeClassifier(random_state=10)
estimators.append(('cart', model2))
model3 = SVC(kernel="rbf",gamma=0.1,C=70)
estimators.append(('svm', model3))
print(estimators)

[('cart', DecisionTreeClassifier(random_state=10)), ('svm', SVC(C=70, gamma=0.1))]


In [43]:
# create the ensemble model
ensemble = VotingClassifier(estimators)
ensemble.fit(X_train,Y_train)
Y_pred=ensemble.predict(X_test)
#print(Y_pred)

In [44]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
#confusion matrix
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[102   0   0   0]
 [  2  19   0   0]
 [  0   0 371   0]
 [  1   0   0  24]]
0.9942196531791907
              precision    recall  f1-score   support

           0       0.97      1.00      0.99       102
           1       1.00      0.90      0.95        21
           2       1.00      1.00      1.00       371
           3       1.00      0.96      0.98        25

    accuracy                           0.99       519
   macro avg       0.99      0.97      0.98       519
weighted avg       0.99      0.99      0.99       519

